### ISSUE TITLE
Moving from 8.0.2 to 8.1.2 causes many "Cannot resolve module" errors with Webpack.

### ISSUE THREAD

**Issue by dschissler** [postcss/postcss-import#220]
I'm using:
- webpack 1.13.1
- postcss 5.0.21
- postcss-cssnext 2.5.2

When I bump from postcss-import 8.0.2 to 8.1.2 then I get the following errors:

```
ERROR in ./~/request/lib/har.js
Module not found: Error: Cannot resolve module 'fs' in /project_path/node_modules/request/lib
 @ ./~/request/lib/har.js 3:9-22

ERROR in ./~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'net' in /project_path/node_modules/forever-agent
 @ ./~/forever-agent/index.js 6:10-24

ERROR in ./~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in /project_path/node_modules/forever-agent
 @ ./~/forever-agent/index.js 7:10-24

ERROR in ./~/tough-cookie/lib/cookie.js
Module not found: Error: Cannot resolve module 'net' in /project_path/node_modules/tough-cookie/lib
 @ ./~/tough-cookie/lib/cookie.js 32:10-24

ERROR in ./~/form-data/lib/form_data.js
Module not found: Error: Cannot resolve module 'fs' in /project_path/node_modules/form-data/lib
 @ ./~/form-data/lib/form_data.js 7:9-22

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'net' in /project_path/node_modules/tunnel-agent
 @ ./~/tunnel-agent/index.js 3:10-24

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in /project_path/node_modules/tunnel-agent
 @ ./~/tunnel-agent/index.js 4:10-24
```

I tried adding the following to my webpack config but it doesn't work:

```
  node: {
    net: 'empty',
    tls: 'empty',
    fs: 'empty'
  },
```

**Comment by glennreyes** [comment]
Same here

**Comment by Garbee** [comment]
Can you please provide some sample code that produces this problem?

**Comment by dschissler** [comment]
I don't think that I will be able to do that soon.  All of my environments are quite complex.

**Comment by s-panferov** [comment]
Can't use this version with webpack:

```
ERROR in (webpack)/hot/only-dev-server.js
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/Users/panferov/Workspace/revjet/csp-react/demo/fs'
	Error: ENOENT: no such file or directory, open '/Users/panferov/Workspace/revjet/csp-react/demo/fs'
	    at Error (native)
	Error loading /Users/panferov/Workspace/revjet/csp-react/demo/fs as "fs" from /Users/panferov/Workspace/revjet/csp-webpack/src/babel-loader.js
 @ multi index

ERROR in (webpack)-dev-server/client?http://localhost:8080
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/Users/panferov/Workspace/revjet/csp-react/demo/fs'
	Error: ENOENT: no such file or directory, open '/Users/panferov/Workspace/revjet/csp-react/demo/fs'
	    at Error (native)
	Error loading /Users/panferov/Workspace/revjet/csp-react/demo/fs as "fs" from /Users/panferov/Workspace/revjet/csp-webpack/src/babel-loader.js
 @ multi index

ERROR in ./src/entry.js
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/Users/panferov/Workspace/revjet/csp-react/demo/path'
	Error: ENOENT: no such file or directory, open '/Users/panferov/Workspace/revjet/csp-react/demo/path'
	    at Error (native)
	Error loading /Users/panferov/Workspace/revjet/csp-react/demo/path as "path" from /Users/panferov/Workspace/revjet/csp-webpack/node_modules/react-hot-loader/index.js
 @ multi index
```

All `require` calls in js files are broken.

**Comment by longlho** [comment]
I'm seeing this issue also

**Comment by longlho** [comment]
some more details: `postcss-import@8.1.0` works, but not `8.1.1` or `8.1.2`

**Comment by Garbee** [comment]
Sorry, don't have the time to look into this myself anymore. We are using Sass now for import/mixins/etc. Then using PostCSS to supplement that with the pieces that will go to browsers like `color` and custom properties.

**Comment by MoOx** [comment]
Guys, use v7, see #210

**Comment by glennreyes** [comment]
I agree with `postcss-import@8.1.0` working on my machine as well.

I'm getting following error if I try to run karma with `8.1.1`:

```
ERROR in ./internals/testing/testbundler.js
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/Users/glennreyes/Projects/iwannahelp/babel-core'
	Error: ENOENT: no such file or directory, open '/Users/glennreyes/Projects/iwannahelp/babel-core'
	    at Error (native)
	Error loading /Users/glennreyes/Projects/iwannahelp/babel-core as "babel-core" from /Users/glennreyes/Projects/iwannahelp/node_modules/babel-loader/index.js
```

cc @longlho

**Comment by langri-sha** [comment]
Have configuration comparable to @longlho. I'm a new user, so if my feedback is of any help, issue only became apparent after adding a `url()` in the stylesheet.

**Comment by KidkArolis** [comment]
Might be related to https://github.com/webpack/webpack/issues/2901? I have a repo that reproduces the bug here: https://github.com/KidkArolis/webpack-2-failing-build. If this is unrelated - let me know and I'll post this as a separate issue.

**Comment by MoOx** [comment]
It seems nobody reads other issues #210.

**Comment by wmertens** [comment]
Just pointing out that the reason of this breaking is explained at  https://github.com/webpack/webpack/issues/2411#issuecomment-247132992

**Comment by Kovensky** [comment]
Version 8.1.3 was released that still has this issue.

Current `master` has a commit that makes the `jspm` dependency optional, but that still won't help as `npm` will still install it, unless you disable optional dependencies; but if you do, it then won't install desirable optional dependencies like `fsevents`.

Unfortunately there are no "optional peerDependencies" :/

**Comment by dschissler** [comment]
I was having this issue when I was using `ampersand` packages but once I switched to `vue` then I was able to upgrade to `8.1.2`.

**Comment by RyanZim** [comment]
> Version 8.1.3 was released that still has this issue.

I know, v8.1.3 only fixed https://github.com/postcss/postcss-import/issues/168.

> Current master has a commit that makes the jspm dependency optional, but that still won't help as npm will still install it, unless you disable optional dependencies; but if you do, it then won't install desirable optional dependencies like fsevents.

Yeah, I wasn't thinking when I did that. I'm currently considering adding a `jspm` option to turn off jspm resolving; see https://github.com/postcss/postcss-import/issues/212.

**Comment by RyanZim** [comment]
A PR (hopefully) fixing this has been merged to the `v9-dev` branch (https://github.com/postcss/postcss-import/pull/243). Can someone install the `v9-dev` branch in their project and confirm that this issue is fixed on that branch? Thanks!

**Comment by code4aman** [comment]
@RyanZim in my case this issue still remains. Currently I'm on `8.1.0` + `webpack@2.1.0-beta.27` and configured PostCSS via `package.json`. The error I get with `v9` is similar to error from `8.1.1` (and up to `8.2.0`).

**Comment by RyanZim** [comment]
@code4aman Can you post the error message here?

**Comment by code4aman** [comment]
@RyanZim here it is.
<details><summary>error log</summary>
```cmd
ERROR in ./client/helpers/fetch.js
Module build failed: (SystemJS) ENOENT: no such file or directory, open 'C:\Users\amank\dev\projname\C:\Users\amank\dev\projname\node_modules\babel-loader\index.js'
        Error: ENOENT: no such file or directory, open 'C:\Users\amank\dev\projname\C:\Users\amank\dev\projname\node_modules\babel-loader\index.js'
        Error loading C:/Users/amank/dev/projname/C:\Users\amank\dev\projname\node_modules\babel-loader\index.js
 @ ./client/pages/Roles/Create/actions.js 2:0-42
 @ ./client/pages/Roles/Create/reducers.js
 @ ./client/combinedReducers.js
 @ ./client/configureStore.js
 @ ./client/index.js
 @ multi main

ERROR in ./client/components/Main/styles.pcss
Module build failed: (SystemJS) ENOENT: no such file or directory, open 'C:\Users\amank\dev\projname\C:\Users\amank\dev\projname\node_modules\style-loader\index.js'
        Error: ENOENT: no such file or directory, open 'C:\Users\amank\dev\projname\C:\Users\amank\dev\projname\node_modules\style-loader\index.js'
        Error loading C:/Users/amank/dev/projname/C:\Users\amank\dev\projname\node_modules\style-loader\index.js
 @ ./client/components/Main/Main.jsx 5:0-30
 @ ./client/components/Main/index.js
 @ ./client/Layout.jsx
 @ ./client/App.jsx
 @ ./client/index.js
 @ multi main
```
</details>

**Comment by Kovensky** [comment]
@code4aman try running `npm prune` to remove the `pkg-resolve` dependency. `postcss-loader@9` will still try to load it if it is available.

**Comment by code4aman** [comment]
@Kovensky @RyanZim `npm prune` did the trick! Looks like it's OK now for me.

**Comment by RyanZim** [comment]
Good to hear, closing. Will try to get v9 shipped as soon as I can.
